version: "3"
services:
  uwsgi:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - WAKe_server/.env
  nginx:
    ports:
      - 80:80
    build: ./nginx
    depends_on :
      - uwsgi