# Generated by Django 5.0.4 on 2024-08-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_ghost",
            field=models.BooleanField(default=False),
        ),
    ]
