name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Setting Secrets
      env:
        ENV_SETTINGS_MODE: 'git'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_STORAGE_BUCKET_NAME: ${{ secrets.AWS_STORAGE_BUCKET_NAME }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_S3_CUSTOM_DOMAIN: ${{ secrets.AWS_S3_CUSTOM_DOMAIN }}
      run: |
        echo ${{ ENV_SETTINGS_MODE }}
        echo ${{ AWS_ACCESS_KEY_ID }}
        echo ${{ AWS_SECRET_ACCESS_KEY }}
        echo ${{ AWS_STORAGE_BUCKET_NAME }}
        echo ${{ AWS_REGION }}
        echo ${{ AWS_S3_CUSTOM_DOMAIN }}
    - name: Run Tests
      run: |
        python manage.py test
